#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "server {
	listen 80;
	listen [::]:80 default_server;

	root   /var/www/html;
	index  index.html index.htm index.nginx-debian.html;
	
	location / {
		return 200 \"Hello World!\n\";
	}

	location /redirect_me {
		 Redirect 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" >/etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
